### ISSUE TITLE
missing schematic config.yml

### ISSUE THREAD

**Issue by jmvera255** [VEOIBD/data_models#63]
@danlu1 Should there be a schematic config.yml file in this repo? I only see `_config.yml` for Jekyll site

**Comment by jmvera255** [comment]
it looks like a schematic config is defined in [VEOIBD:data_curator](https://github.com/VEOIBD/data_curator) and that that's the config the DCA uses, but for HTAN data-model repo there is also a config.yml and just curious about what to use as a config for the VEOIBD model when running schematic from the command line. My attempts to make one are resulting in errors.

**Comment by danlu1** [comment]
@jmvera255 This is a repo that we used to hold data models and run steps to prepare data models in a format that can be digested by the DCA. The design of the [Jekyll site]([veoibd.github.io/data_models/](https://veoibd.github.io/data_models/)) is VEOIBD-specific. We didn't adapt their infrastructure. Also, we don't have to have a schematic config file since DCA will simply pull the data mode in this [file](https://github.com/Sage-Bionetworks/data_curator_config/blob/78b4eab173c7af3ce229a9e1db91faf1c46db9ec/VEOIBD/dca_config.json#L5) and this [file](https://github.com/VEOIBD/data_curator_config/blob/main/dcc_config.csv) (we used to use this one but not if this changed) which are host in FAIR data team repos.

**Comment by jmvera255** [comment]
As Dan described, no schematic-specific `config.yml` is required in this repo. I was able to create a config locally and use that to run some schematic commands.
